import { IconType } from "react-icons";

import {
  HiMiniMinus,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiMiniPlus,
  HiOutlineMagnifyingGlass,
  HiCalendar,
  HiOutlineLink,
  HiArrowUpRight,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineBars3BottomLeft,
  HiOutlineHome,
  HiOutlineAcademicCap,
  HiOutlineQueueList,
  HiOutlineRocketLaunch,
  HiOutlineIdentification,
  HiOutlinePhoto,
  HiOutlineMap,
  HiOutlineClock,
  HiOutlineLightBulb,
  HiOutlineAdjustmentsHorizontal,
  HiOutlinePaintBrush,
  HiOutlineDocumentDuplicate,
  HiOutlineDocumentText,
  HiOutlineSquare3Stack3D,
  HiOutlineLanguage,
  HiOutlineCube,
  HiOutlineBars3,
  HiOutlineKey,
} from "react-icons/hi2";

import { RiVisaLine } from "react-icons/ri";

import { FaDiscord, FaGithub, FaGoogle, FaLinkedin, FaMailchimp, FaThreads, FaFacebook, FaInstagram, FaXTwitter, FaTiktok } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  openLink: HiOutlineLink,
  discord: FaDiscord,
  google: FaGoogle,
  github: FaGithub,
  arrowUpRight: HiArrowUpRight,
  minus: HiMiniMinus,
  plus: HiMiniPlus,
  calendar: HiCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  visa: RiVisaLine,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  document: HiOutlineBars3BottomLeft,
  linkedin: FaLinkedin,
  threads: FaThreads,
  facebook: FaFacebook,
  instagram: FaInstagram,
  twitter: FaXTwitter,
  tiktok: FaTiktok,
  home: HiOutlineHome,
  scholar: HiOutlineAcademicCap,
  queue: HiOutlineQueueList,
  rocket: HiOutlineRocketLaunch,
  card: HiOutlineIdentification,
  image: HiOutlinePhoto,
  roadmap: HiOutlineMap,
  lightbulb: HiOutlineLightBulb,
  config: HiOutlineAdjustmentsHorizontal,
  mailchimp: FaMailchimp,
  style: HiOutlinePaintBrush,
  pages: HiOutlineDocumentDuplicate,
  learn: HiOutlineAcademicCap,
  page: HiOutlineDocumentText,
  project: HiOutlineSquare3Stack3D,
  article: HiOutlineQueueList,
  language: HiOutlineLanguage,
  components: HiOutlineCube,
  sidebar: HiOutlineBars3,
  password: HiOutlineKey,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;